### ISSUE TITLE
Navigation display bug in Chrome (Windows)

### ISSUE THREAD

**Issue by rachgo** [bigcartel-themes/luna#110]
Category links are wonky:
http://www.bridlewaybarn.co.uk/products

![image001](https://cloud.githubusercontent.com/assets/3578349/5191880/dfbb2460-74b7-11e4-8f74-b241044781bf.png)

And header nav/category links:
http://simplyscandinavian.bigcartel.com/products

![product categories](https://cloud.githubusercontent.com/assets/3578349/5191912/26404906-74b8-11e4-933e-8cdbc0cacd6a.jpg)

Was able to reproduce in Browserstack using Windows 8.1 and Chrome 39.

**Comment by nickendle** [comment]
@rachgo i'm guessing we probably haven't heard/seen anything more about this?

**Comment by rachgo** [comment]
I haven't heard anything since those last two ^

**Comment by nickendle** [comment]
Thanks! Chrome is at 40 now and due to the auto-updating it's pretty unlikely we'll see any more reports... Gonna close.
