### ISSUE TITLE
Header title wraps on mobile browsers

### ISSUE THREAD

**Issue by JoeyCruzingtonIII** [bigcartel-themes/luna#115]
Longer store names (example: LAINEYORIGINAL) will wrap on mobile browsers depending on the browser and font width. iPhone 5 seems to be the worst culprit - could not find a single font that would allow the entire title to fit on one line. 

Attached screenshots show Times New Roman.

Tested fonts:
Helvetica
Times New Roman
Monsterat
Vampire One
Verela Round
Impact
Titillium Web

Tested in browserstack on:
iPhone 5
iPhone 6S
Lumia 930
Samsung Galaxy S5

<img width="378" alt="galaxys5-timesnewroman" src="https://cloud.githubusercontent.com/assets/14612155/11905187/c4bc75b2-a579-11e5-8726-1fb60c870c33.png">
<img width="422" alt="iphone5-timesnewroman" src="https://cloud.githubusercontent.com/assets/14612155/11905190/c4fac7cc-a579-11e5-86a4-737e7f6c9a41.png">
<img width="369" alt="iphone6s-timesnewroman" src="https://cloud.githubusercontent.com/assets/14612155/11905188/c4ec085e-a579-11e5-8819-d9f7874612e5.png">
<img width="415" alt="lumia930-timesnewroman" src="https://cloud.githubusercontent.com/assets/14612155/11905189/c4f143a0-a579-11e5-9d4e-85fa90d12ef7.png">

**Comment by nickendle** [comment]
@JoeyCruzingtonIII i'm curious for this case in particular how the store owner expects this to be handled. we could of course make the font size smaller for screens, and "LAINEYORIGINAL" would fit - but there could be cases where the title will be a few characters longer and you can only make the font size so small...

**Comment by JoeyCruzingtonIII** [comment]
@nickendle Hey! Sorry for not seeing this sooner. In this case, I believe the store owner was hoping the title font would resize to accommodate the width of the mobile screen. She has since uploaded a logo image that does the job (which you can see in action here: http://laineyoriginals.bigcartel.com). Still, when I brought the original issue to SF's attention, they thought I should submit it as a bug.
